FROM lucianojr/quotes-api-php:latest

COPY ./docker/php/conf/php.prod.ini /usr/local/etc/php/php.ini

COPY ./app /var/www/app

COPY ./docker/php/scripts/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint
ENTRYPOINT ["/usr/local/bin/docker-entrypoint"]

CMD ["php-fpm"]
